"""Generate docs/catalog.md + thumbnails from published release data.

Uses the mat-vis client to fetch 128px textures and index metadata
directly from the release — no upstream download, no local bake needed.

Usage:
    mat-vis-baker catalog-from-release v2026.04.0 --output-dir .
"""

from __future__ import annotations

import json
import logging
import sys
from pathlib import Path

log = logging.getLogger("mat-vis-baker.catalog-from-release")

# ── catalog markdown generation ─────────────────────────────────

HEADER = """\
<!-- AUTO-GENERATED by mat-vis-baker — do not edit manually -->
<!-- Source: release {tag} | Generated: {date} -->

# Material Catalog

> **{total}** materials across **{n_sources}** sources, **{n_tiers}** resolution tiers.
>
> Browse by source → category. Click a material name to view it on the upstream site.
> Thumbnails are 128px previews — full textures available via
> [`pip install mat-vis-client`](https://pypi.org/project/mat-vis-client/).
>
> ```python
> from mat_vis_client import MatVisClient
> client = MatVisClient()
> png = client.fetch_texture("ambientcg", "Rock064", "color", tier="1k")
> ```

---

**Quick links:** {source_links}

---

"""

SOURCE_HEADER = """\
## {icon} {source}

> {count} materials | Tiers: {tiers} | License: {license}
> [{source_url}]({source_url})

"""

SCALAR_HEADER = """\
## {icon} {source} — scalar properties

> {count} materials | No textures — IOR, roughness, metalness, color values
> [{source_url}]({source_url})

"""

SOURCE_ICONS = {
    "ambientcg": "🪨",
    "polyhaven": "🏔️",
    "gpuopen": "💎",
    "physicallybased": "⚛️",
}

SOURCE_URLS = {
    "ambientcg": "https://ambientcg.com",
    "polyhaven": "https://polyhaven.com",
    "gpuopen": "https://matlib.gpuopen.com",
    "physicallybased": "https://physicallybased.info",
}

SOURCE_LICENSES = {
    "ambientcg": "CC0-1.0",
    "polyhaven": "CC0-1.0",
    "gpuopen": "TBV (per material)",
    "physicallybased": "CC0-1.0",
}

TEXTURE_SOURCES = ["ambientcg", "polyhaven", "gpuopen"]
SCALAR_SOURCES = ["physicallybased"]


def _thumb_img(source: str, material_id: str, channel: str) -> str:
    """Markdown image for a thumbnail committed to git."""
    return f"![{channel}](../mtlx/{source}/{material_id}/{channel}_thumb.png)"


def _material_link(source: str, material_id: str, name: str) -> str:
    """Link to upstream material page."""
    urls = {
        "ambientcg": f"https://ambientcg.com/a/{material_id}",
        "polyhaven": f"https://polyhaven.com/a/{material_id}",
        "gpuopen": f"https://matlib.gpuopen.com/main/materials/all?material={material_id}",
        "physicallybased": "https://physicallybased.info",
    }
    return f"[{name}]({urls.get(source, '#')})"


def generate_catalog_from_release(
    tag: str,
    thumb_dir: Path,
    index_dir: Path | None = None,
) -> str:
    """Generate catalog markdown from release manifest + index JSONs.

    Args:
        tag: Release tag (e.g. v2026.04.0)
        thumb_dir: Where thumbnails are stored (mtlx/<source>/<id>/)
        index_dir: Where index JSONs are (index/). If None, downloads from release.
    """
    from collections import defaultdict
    from datetime import datetime

    # Load manifest to discover sources × tiers
    try:
        import urllib.request

        manifest_url = (
            f"https://github.com/MorePET/mat-vis/releases/download/{tag}/release-manifest.json"
        )
        manifest = json.loads(urllib.request.urlopen(manifest_url).read())
    except Exception:
        log.error("Failed to fetch manifest for %s", tag)
        return ""

    all_tiers = sorted(manifest.get("tiers", {}).keys())
    all_sources: set[str] = set()
    for tier_data in manifest["tiers"].values():
        all_sources.update(tier_data.get("sources", {}).keys())

    # Load index JSONs
    indexes: dict[str, list[dict]] = {}
    for source in sorted(all_sources):
        if index_dir and (index_dir / f"{source}.json").exists():
            indexes[source] = json.loads((index_dir / f"{source}.json").read_text())
        else:
            try:
                url = f"https://github.com/MorePET/mat-vis/releases/download/{tag}/{source}.json"
                indexes[source] = json.loads(urllib.request.urlopen(url).read())
            except Exception:
                log.warning("No index for %s", source)

    # Also try physicallybased
    if "physicallybased" not in indexes:
        try:
            url = f"https://github.com/MorePET/mat-vis/releases/download/{tag}/physicallybased.json"
            indexes["physicallybased"] = json.loads(urllib.request.urlopen(url).read())
        except Exception:
            pass

    # Count totals
    total = sum(len(v) for v in indexes.values())
    n_sources = len(indexes)

    source_links = " | ".join(
        f"[{SOURCE_ICONS.get(s, '📦')} {s}](#{s})" for s in sorted(indexes.keys())
    )

    sections: list[str] = []

    # Header
    sections.append(
        HEADER.format(
            tag=tag,
            date=datetime.now().strftime("%Y-%m-%d"),
            total=total,
            n_sources=n_sources,
            n_tiers=len(all_tiers),
            source_links=source_links,
        )
    )

    # Texture sources
    for source in TEXTURE_SOURCES:
        if source not in indexes:
            continue
        entries = indexes[source]
        ok_entries = [e for e in entries if e.get("status") != "failed"]
        if not ok_entries:
            continue

        # Determine which tiers this source has
        source_tiers = [
            t for t in all_tiers if source in manifest["tiers"].get(t, {}).get("sources", {})
        ]

        sections.append(
            SOURCE_HEADER.format(
                icon=SOURCE_ICONS.get(source, "📦"),
                source=source,
                count=len(ok_entries),
                tiers=", ".join(source_tiers),
                license=SOURCE_LICENSES.get(source, "unknown"),
                source_url=SOURCE_URLS.get(source, ""),
            )
        )

        # Group by category
        by_cat: dict[str, list[dict]] = defaultdict(list)
        for e in ok_entries:
            by_cat[e.get("category", "other")].append(e)

        for cat in sorted(by_cat.keys()):
            cat_entries = sorted(by_cat[cat], key=lambda e: e["id"])
            sections.append(f"<details><summary><b>{cat}</b> ({len(cat_entries)})</summary>\n")
            sections.append("| | Material | Maps | Category |")
            sections.append("|---|---|---|---|")

            for entry in cat_entries:
                mid = entry["id"]
                name = entry.get("name", mid)
                link = _material_link(source, mid, name)
                maps = ", ".join(entry.get("maps", []))

                # Thumbnail
                color_thumb = thumb_dir / source / mid / "color_thumb.png"
                if color_thumb.exists():
                    thumb = _thumb_img(source, mid, "color")
                else:
                    thumb = "—"

                sections.append(f"| {thumb} | {link} | {maps} | {cat} |")

            sections.append("\n</details>\n")

    # Scalar sources
    for source in SCALAR_SOURCES:
        if source not in indexes:
            continue
        entries = indexes[source]
        if not entries:
            continue

        sections.append(
            SCALAR_HEADER.format(
                icon=SOURCE_ICONS.get(source, "📦"),
                source=source,
                count=len(entries),
                source_url=SOURCE_URLS.get(source, ""),
            )
        )

        by_cat: dict[str, list[dict]] = defaultdict(list)
        for e in entries:
            by_cat[e.get("category", "other")].append(e)

        for cat in sorted(by_cat.keys()):
            cat_entries = sorted(by_cat[cat], key=lambda e: e["id"])
            sections.append(f"<details><summary><b>{cat}</b> ({len(cat_entries)})</summary>\n")
            sections.append("| Material | Color | Roughness | Metalness | IOR |")
            sections.append("|---|---|---|---|---|")

            for entry in cat_entries:
                name = entry.get("name", entry["id"])
                color = entry.get("color_hex")
                rough = entry.get("roughness")
                metal = entry.get("metalness")
                ior = entry.get("ior")

                color_cell = f"`{color}`" if color else "—"
                rough_str = f"{rough:.2f}" if rough is not None else "—"
                metal_str = f"{metal:.1f}" if metal is not None else "—"
                ior_str = f"{ior:.2f}" if ior is not None else "—"

                sections.append(
                    f"| {name} | {color_cell} | {rough_str} | {metal_str} | {ior_str} |"
                )

            sections.append("\n</details>\n")

    # Footer
    sections.append(
        f"\n---\n*Generated from release `{tag}` on {datetime.now().strftime('%Y-%m-%d %H:%M')} UTC*\n"
    )

    return "\n".join(sections)


def fetch_thumbnails_from_release(
    tag: str,
    thumb_dir: Path,
    tier: str = "128",
) -> int:
    """Download 128px color thumbnails from the release for catalog rendering.

    Uses the client to range-read the color channel at the smallest tier.
    Saves to thumb_dir/<source>/<material_id>/color_thumb.png.
    Returns count of thumbnails saved.
    """
    sys.path.insert(0, str(Path(__file__).parent.parent.parent / "clients" / "python" / "src"))
    try:
        from mat_vis_client import MatVisClient
    except ImportError:
        log.error("mat_vis_client not importable — install with: pip install mat-vis-client")
        return 0

    client = MatVisClient(tag=tag)
    saved = 0

    for source in client.sources(tier):
        materials = client.materials(source, tier)
        log.info("fetching %d thumbnails for %s at %s", len(materials), source, tier)

        for i, mid in enumerate(materials):
            thumb_path = thumb_dir / source / mid / "color_thumb.png"
            if thumb_path.exists():
                saved += 1
                continue

            try:
                png = client.fetch_texture(source, mid, "color", tier)
                thumb_path.parent.mkdir(parents=True, exist_ok=True)
                thumb_path.write_bytes(png)
                saved += 1
            except Exception:
                pass  # skip materials without color channel

            if (i + 1) % 100 == 0:
                log.info("  %s: %d/%d thumbnails", source, i + 1, len(materials))

    log.info("saved %d thumbnails total", saved)
    return saved
