"""Generate docs/catalog.md — a browsable material gallery rendered by GitHub.

Structure:
  # Material Catalog
  ## ambientcg — 50 materials
  ### metal (12)
    <table with thumbnails>
  ### stone (8)
    <table with thumbnails>
  ## physicallybased — 86 materials (scalar only)
  ### metal (45)
    <table with hex swatches>
"""

from __future__ import annotations

import json
import logging
from collections import defaultdict
from pathlib import Path

log = logging.getLogger("mat-vis-baker.catalog")

TEXTURE_SOURCES = ["ambientcg", "polyhaven", "gpuopen"]
SCALAR_SOURCES = ["physicallybased"]

HEADER = """\
<!-- AUTO-GENERATED by mat-vis-baker — do not edit manually -->

# Material Catalog

> {total} materials across {n_sources} sources.
> Textures are served via HTTP range reads from
> [GitHub Releases](https://github.com/MorePET/mat-vis/releases).

"""


def _thumb_img(source: str, material_id: str, channel: str) -> str:
    """Markdown image tag for a committed thumbnail."""
    return f"![{channel}](mtlx/{source}/{material_id}/{channel}_thumb.png)"


def _texture_section(source: str, entries: list[dict], thumb_dir: Path) -> str:
    """Generate a source section with category grouping for texture materials."""
    ok_entries = [e for e in entries if e.get("status") != "failed"]
    if not ok_entries:
        return ""

    tiers = set()
    for e in ok_entries:
        tiers.update(e.get("available_tiers", []))
    tier_str = ", ".join(sorted(tiers)) if tiers else "—"

    # Group by category
    by_cat: dict[str, list[dict]] = defaultdict(list)
    for e in ok_entries:
        by_cat[e.get("category", "other")].append(e)

    lines = [f"## {source} — {len(ok_entries)} materials ({tier_str})\n"]

    for cat in sorted(by_cat.keys()):
        cat_entries = by_cat[cat]
        lines.append(f"<details><summary><b>{cat}</b> ({len(cat_entries)})</summary>\n")
        lines.append("| Material | Color | Normal | Category | License |")
        lines.append("|---|---|---|---|---|")

        for entry in sorted(cat_entries, key=lambda e: e["id"]):
            mid = entry["id"]
            name = entry.get("name", mid)
            lic = entry.get("source_license", "—")
            url = entry.get("source_url", "")
            link = f"[{name}]({url})" if url else name

            color_thumb = thumb_dir / source / mid / "color_thumb.png"
            normal_thumb = thumb_dir / source / mid / "normal_thumb.png"
            color_img = _thumb_img(source, mid, "color") if color_thumb.exists() else "—"
            normal_img = _thumb_img(source, mid, "normal") if normal_thumb.exists() else "—"

            lines.append(f"| {link} | {color_img} | {normal_img} | {cat} | {lic} |")

        lines.append("\n</details>\n")

    return "\n".join(lines)


def _scalar_section(source: str, entries: list[dict]) -> str:
    """Generate a source section with category grouping for scalar materials."""
    if not entries:
        return ""

    by_cat: dict[str, list[dict]] = defaultdict(list)
    for e in entries:
        by_cat[e.get("category", "other")].append(e)

    lines = [f"## {source} — {len(entries)} materials (scalar only)\n"]

    for cat in sorted(by_cat.keys()):
        cat_entries = by_cat[cat]
        lines.append(f"<details><summary><b>{cat}</b> ({len(cat_entries)})</summary>\n")
        lines.append("| Material | Color | Roughness | Metalness | IOR |")
        lines.append("|---|---|---|---|---|")

        for entry in sorted(cat_entries, key=lambda e: e["id"]):
            name = entry.get("name", entry["id"])
            color = entry.get("color_hex")
            rough = entry.get("roughness")
            metal = entry.get("metalness")
            ior = entry.get("ior")

            color_cell = f"`{color}`" if color else "—"
            rough_str = f"{rough:.2f}" if rough is not None else "—"
            metal_str = f"{metal:.1f}" if metal is not None else "—"
            ior_str = f"{ior:.2f}" if ior is not None else "—"

            lines.append(f"| {name} | {color_cell} | {rough_str} | {metal_str} | {ior_str} |")

        lines.append("\n</details>\n")

    return "\n".join(lines)


def generate_catalog(index_dir: Path, thumb_dir: Path) -> str:
    """Generate catalog markdown from index JSONs + thumbnails."""
    sections: list[str] = []
    total = 0
    sources_seen = 0

    for source in TEXTURE_SOURCES:
        index_path = index_dir / f"{source}.json"
        if not index_path.exists():
            continue
        entries = json.loads(index_path.read_text())
        ok = [e for e in entries if e.get("status") != "failed"]
        if ok:
            sources_seen += 1
            total += len(ok)
            sections.append(_texture_section(source, entries, thumb_dir))

    for source in SCALAR_SOURCES:
        index_path = index_dir / f"{source}.json"
        if not index_path.exists():
            continue
        entries = json.loads(index_path.read_text())
        if entries:
            sources_seen += 1
            total += len(entries)
            sections.append(_scalar_section(source, entries))

    header = HEADER.format(total=total, n_sources=sources_seen)
    return header + "\n".join(sections) + "\n"


def write_catalog(catalog_md: str, output_path: Path) -> Path:
    """Write catalog markdown to disk."""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(catalog_md)
    log.info("wrote %s", output_path)
    return output_path
