"""Generate MaterialX XML documents and pack them as a parquet tier.

Two flavors:
  - Generated (mtlx tier): For all three texture sources (ambientcg, polyhaven,
    gpuopen), produce a UsdPreviewSurface-based MaterialX document that
    references hosted PNGs via release URLs.
  - Original (mtlx-original tier): For gpuopen only, pack the upstream .mtlx
    files verbatim.

Output schema: id (string), source (string), category (string), mtlx (binary).
One row group per material for constant-memory streaming.
"""

from __future__ import annotations

import json
import logging
import sys
import time
import xml.etree.ElementTree as ET
from collections import defaultdict
from pathlib import Path

import pyarrow as pa
import pyarrow.parquet as pq

log = logging.getLogger("mat-vis-baker.mtlx-tier")

# ── constants ─────────────────────────────────────────────────────

GITHUB_RELEASES_BASE = "https://github.com/MorePET/mat-vis/releases/download"

# Map canonical channel name to UsdPreviewSurface input name and value type.
_CHANNEL_TO_USD: dict[str, tuple[str, str]] = {
    "color": ("diffuseColor", "color3f"),
    "normal": ("normal", "normal"),
    "roughness": ("roughness", "float"),
    "metalness": ("metallic", "float"),
    "ao": ("occlusion", "float"),
    "displacement": ("displacement", "float"),
    "emission": ("emissiveColor", "color3f"),
}

# MaterialX type strings for image nodes
_MTLX_OUTPUT_TYPES: dict[str, str] = {
    "color3f": "color3",
    "float": "float",
    "normal": "vector3",
}

_MTLX_SCHEMA = pa.schema(
    [
        pa.field("id", pa.string(), nullable=False),
        pa.field("source", pa.string(), nullable=False),
        pa.field("category", pa.string(), nullable=False),
        pa.field("mtlx", pa.binary(), nullable=False),
    ]
)


# ── client helper (same pattern as derive_from_release) ───────────


def _make_client(release_tag: str):
    """Create a MatVisClient, handling the dev-layout import path."""
    try:
        from mat_vis_client import MatVisClient
    except ImportError:
        client_path = str(Path(__file__).resolve().parents[2] / "clients" / "python" / "src")
        if client_path not in sys.path:
            sys.path.insert(0, client_path)
        from mat_vis_client import MatVisClient

    return MatVisClient(tag=release_tag)


# ── XML generation ────────────────────────────────────────────────


def _texture_uri(
    release_tag: str,
    parquet_file: str,
    material_id: str,
    channel: str,
) -> str:
    """Build a custom texture URI pointing into a hosted parquet.

    Format:
        https://github.com/MorePET/mat-vis/releases/download/{tag}/{pq}#range={id}/{ch}

    The consumer's resolver uses the mat-vis client to fetch the actual bytes.
    """
    return f"{GITHUB_RELEASES_BASE}/{release_tag}/{parquet_file}#range={material_id}/{channel}"


def generate_mtlx_document(
    material_id: str,
    source: str,
    channels: dict[str, str],
    release_tag: str,
    tier: str = "1k",
) -> bytes:
    """Generate a MaterialX XML document for a single material.

    Args:
        material_id: Unique material identifier (e.g. ``Rock064``).
        source: Texture source name (``ambientcg``, ``polyhaven``, ``gpuopen``).
        channels: Mapping of canonical channel name to the parquet filename
                  that contains it (e.g. ``{"color": "mat-vis-ambientcg-1k-stone.parquet"}``).
        release_tag: GitHub release tag (e.g. ``v2026.04.0``).
        tier: Resolution tier string (default ``1k``).

    Returns:
        UTF-8 encoded XML bytes of a valid MaterialX 1.38 document.
    """
    root = ET.Element("materialx")
    root.set("version", "1.38")
    root.set("xmlns", "http://www.materialx.org/")

    # Comment header
    root.append(ET.Comment(f" material: {material_id} "))
    root.append(ET.Comment(f" source: {source} "))
    root.append(ET.Comment(f" tier: {tier} "))
    root.append(ET.Comment(" generated by mat-vis-baker "))

    # Node graph containing texture reads
    nodegraph_name = f"{material_id}_textures"
    nodegraph = ET.SubElement(root, "nodegraph", name=nodegraph_name)

    output_refs: dict[str, tuple[str, str]] = {}  # usd_input -> (output_name, mtlx_type)

    for ch_name, (usd_input, val_type) in _CHANNEL_TO_USD.items():
        if ch_name not in channels:
            continue

        parquet_file = channels[ch_name]
        uri = _texture_uri(release_tag, parquet_file, material_id, ch_name)
        mtlx_type = _MTLX_OUTPUT_TYPES[val_type]

        img_node_name = f"img_{ch_name}"
        img = ET.SubElement(nodegraph, "image", name=img_node_name, type=mtlx_type)
        file_input = ET.SubElement(img, "input", name="file", type="filename")
        file_input.set("value", uri)

        if ch_name == "color":
            file_input.set("colorspace", "srgb_texture")
        elif ch_name == "emission":
            file_input.set("colorspace", "srgb_texture")

        # For normal maps, add a normalmap node
        if ch_name == "normal":
            nmap_name = f"normalmap_{ch_name}"
            nmap = ET.SubElement(nodegraph, "normalmap", name=nmap_name, type="vector3")
            nmap_in = ET.SubElement(nmap, "input", name="in", type="vector3")
            nmap_in.set("nodename", img_node_name)

            out_name = f"out_{ch_name}"
            out = ET.SubElement(nodegraph, "output", name=out_name, type="vector3")
            out.set("nodename", nmap_name)
            output_refs[usd_input] = (out_name, "vector3")
        else:
            out_name = f"out_{ch_name}"
            out = ET.SubElement(nodegraph, "output", name=out_name, type=mtlx_type)
            out.set("nodename", img_node_name)
            output_refs[usd_input] = (out_name, mtlx_type)

    # UsdPreviewSurface shader node
    shader_name = f"{material_id}_shader"
    shader = ET.SubElement(root, "UsdPreviewSurface", name=shader_name, type="surfaceshader")

    for usd_input, (out_name, mtlx_type) in output_refs.items():
        inp = ET.SubElement(shader, "input", name=usd_input, type=mtlx_type)
        inp.set("nodegraph", nodegraph_name)
        inp.set("output", out_name)

    # Surface material
    mat = ET.SubElement(root, "surfacematerial", name=material_id, type="material")
    mat_inp = ET.SubElement(mat, "input", name="surfaceshader", type="surfaceshader")
    mat_inp.set("nodename", shader_name)

    # Render to indented XML
    ET.indent(root, space="  ")
    xml_bytes = ET.tostring(root, encoding="unicode", xml_declaration=True)
    return xml_bytes.encode("utf-8")


# ── pack generated mtlx tier ─────────────────────────────────────


def pack_mtlx_tier(
    tag: str,
    tier: str,
    output_dir: Path,
    sources: list[str] | None = None,
    *,
    _client=None,
) -> list[Path]:
    """Generate MaterialX documents for all materials and pack into parquet.

    Streams one row at a time for constant memory. Produces one parquet file
    per source x category, plus a companion rowmap JSON.

    Args:
        tag: GitHub release tag to reference in texture URIs.
        tier: Resolution tier (e.g. ``1k``).
        output_dir: Directory to write parquet and rowmap files into.
        sources: Restrict to these sources. ``None`` means all available.
        _client: Optional pre-built client (for testing).

    Returns:
        List of parquet file paths written.
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    t0 = time.monotonic()

    client = _client or _make_client(tag)

    if sources is None:
        sources = client.sources(tier)

    all_paths: list[Path] = []

    for source in sources:
        log.info("pack_mtlx_tier: %s %s (tag %s)", source, tier, tag)

        material_ids = client.materials(source, tier)
        index_entries = client.index(source)
        index_by_id = {e["id"]: e for e in index_entries}

        # Lazy writers per category
        writers: dict[str, pq.ParquetWriter] = {}
        category_paths: dict[str, Path] = {}
        rowmap_materials: dict[str, dict[str, dict[str, dict[str, int]]]] = defaultdict(dict)
        n_ok = 0

        try:
            for i, mid in enumerate(material_ids):
                entry = index_by_id.get(mid, {})
                category = entry.get("category", "other")

                available_channels = client.channels(source, mid, tier)
                if not available_channels:
                    log.warning("[%d/%d] %s: no channels, skipping", i + 1, len(material_ids), mid)
                    continue

                # Build channels dict: canonical_channel -> parquet_file
                # Determine the parquet file from the rowmap
                rm = client.rowmap(source, tier)
                mat_rm = rm.get("materials", {}).get(mid, {})
                ch_to_pq: dict[str, str] = {}
                for ch in available_channels:
                    ch_info = mat_rm.get(ch, {})
                    pq_file = ch_info.get(
                        "parquet_file", f"mat-vis-{source}-{tier}-{category}.parquet"
                    )
                    ch_to_pq[ch] = pq_file

                mtlx_xml = generate_mtlx_document(mid, source, ch_to_pq, tag, tier)

                row = {
                    "id": [mid],
                    "source": [source],
                    "category": [category],
                    "mtlx": [mtlx_xml],
                }

                # Lazy-open writer for this category
                if category not in writers:
                    pq_name = f"mat-vis-{source}-mtlx-{category}.parquet"
                    pq_path = output_dir / pq_name
                    category_paths[category] = pq_path
                    writers[category] = pq.ParquetWriter(
                        pq_path,
                        _MTLX_SCHEMA,
                        compression="ZSTD",
                    )

                table = pa.table(row, schema=_MTLX_SCHEMA)
                writers[category].write_table(table)

                # Track for rowmap: mtlx column offset will be resolved after
                # writing, so just record the material for later.
                rowmap_materials[category][mid] = {
                    "mtlx": {"offset": 0, "length": len(mtlx_xml)},
                }

                n_ok += 1
                del row, table

                if (i + 1) % 100 == 0 or (i + 1) == len(material_ids):
                    log.info(
                        "[%d/%d] %s mtlx: %d ok (%.1fs)",
                        i + 1,
                        len(material_ids),
                        source,
                        n_ok,
                        time.monotonic() - t0,
                    )
        finally:
            for w in writers.values():
                w.close()

        # Generate rowmaps with actual byte offsets from the written parquets
        for category, pq_path in sorted(category_paths.items()):
            rowmap = _generate_mtlx_rowmap(pq_path, source, category, tag)
            rm_path = output_dir / f"{source}-mtlx-{category}-rowmap.json"
            rm_path.write_text(json.dumps(rowmap, indent=2) + "\n")
            log.info("wrote %s", rm_path)
            all_paths.append(pq_path)

        log.info(
            "pack_mtlx_tier: %s done — %d materials in %.1fs",
            source,
            n_ok,
            time.monotonic() - t0,
        )

    return all_paths


def _generate_mtlx_rowmap(
    parquet_path: Path,
    source: str,
    category: str,
    release_tag: str,
) -> dict:
    """Generate a rowmap for an mtlx-tier parquet.

    Each row group has one material. The rowmap records the byte offset and
    length of the ``mtlx`` column's data page so consumers can range-read
    just the XML for a single material.
    """
    pf = pq.ParquetFile(parquet_path)
    meta = pf.metadata

    # Find the column index for 'mtlx'
    mtlx_col_idx: int | None = None
    for idx, field in enumerate(pf.schema_arrow):
        if field.name == "mtlx":
            mtlx_col_idx = idx
            break

    if mtlx_col_idx is None:
        raise ValueError(f"'mtlx' column not found in {parquet_path}")

    materials: dict[str, dict[str, dict[str, int]]] = {}

    for rg_idx in range(meta.num_row_groups):
        rg = meta.row_group(rg_idx)

        # Read material ID
        table = pf.read_row_group(rg_idx, columns=["id"])
        mid = table.column("id")[0].as_py()

        col_meta = rg.column(mtlx_col_idx)
        offset = col_meta.data_page_offset
        length = col_meta.total_compressed_size

        materials[mid] = {
            "mtlx": {"offset": offset, "length": length},
        }

    return {
        "version": 1,
        "release_tag": release_tag,
        "source": source,
        "tier": "mtlx",
        "category": category,
        "parquet_file": parquet_path.name,
        "materials": materials,
    }


# ── pack original upstream mtlx ──────────────────────────────────


def pack_original_mtlx(
    mtlx_dir: Path,
    source: str,
    output_dir: Path,
    release_tag: str,
) -> list[Path]:
    """Pack original upstream MaterialX files into parquet.

    Reads ``.mtlx`` files from ``mtlx_dir/{source}/`` and writes them into
    parquet files partitioned by category.

    Args:
        mtlx_dir: Root directory containing per-source subdirectories
                  (e.g. ``mtlx/gpuopen/MaterialName/material.mtlx``).
        source: Source name (e.g. ``gpuopen``).
        output_dir: Where to write output parquet files.
        release_tag: Tag for the rowmap metadata.

    Returns:
        List of parquet file paths written.
    """
    from mat_vis_baker.common import normalize_category

    output_dir.mkdir(parents=True, exist_ok=True)
    source_dir = mtlx_dir / source

    if not source_dir.is_dir():
        log.error("source directory does not exist: %s", source_dir)
        return []

    # Collect all .mtlx files
    mtlx_files = sorted(source_dir.rglob("*.mtlx"))
    if not mtlx_files:
        log.warning("no .mtlx files found in %s", source_dir)
        return []

    log.info("pack_original_mtlx: %d .mtlx files in %s", len(mtlx_files), source_dir)

    writers: dict[str, pq.ParquetWriter] = {}
    category_paths: dict[str, Path] = {}
    n_ok = 0

    try:
        for mtlx_path in mtlx_files:
            # Derive material ID from parent directory name (MaterialName/material.mtlx)
            # or from filename if flat (MaterialName.mtlx)
            if mtlx_path.name == "material.mtlx":
                material_id = mtlx_path.parent.name
            else:
                material_id = mtlx_path.stem

            category = normalize_category(material_id)
            mtlx_bytes = mtlx_path.read_bytes()

            row = {
                "id": [material_id],
                "source": [source],
                "category": [category],
                "mtlx": [mtlx_bytes],
            }

            if category not in writers:
                pq_name = f"mat-vis-{source}-mtlx-original-{category}.parquet"
                pq_path = output_dir / pq_name
                category_paths[category] = pq_path
                writers[category] = pq.ParquetWriter(
                    pq_path,
                    _MTLX_SCHEMA,
                    compression="ZSTD",
                )

            table = pa.table(row, schema=_MTLX_SCHEMA)
            writers[category].write_table(table)
            n_ok += 1
            del row, table
    finally:
        for w in writers.values():
            w.close()

    # Generate rowmaps
    paths: list[Path] = []
    for category, pq_path in sorted(category_paths.items()):
        rowmap = _generate_mtlx_rowmap(pq_path, source, category, release_tag)
        rowmap["tier"] = "mtlx-original"
        rm_path = output_dir / f"{source}-mtlx-original-{category}-rowmap.json"
        rm_path.write_text(json.dumps(rowmap, indent=2) + "\n")
        log.info("wrote %s", rm_path)
        paths.append(pq_path)

    log.info("pack_original_mtlx: %s done — %d materials", source, n_ok)
    return paths
